/* Required Notice: Copyright (c) 2025 Robert E. Smith <robert.smith@florey.edu.au>;
 * Required Notice: The Florey Institute of Neuroscience and Mental Health.
 *
 * Licensed under the PolyForm Noncommercial License 1.0.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     https://polyformproject.org/licenses/noncommercial/1.0.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 * See the License of the specific language
 * governing permissions and limitations under the License.
 */

#include <string>

#include "command.h"
#include "filter/demodulate.h"
#include "header.h"
#include "image.h"
#include "math/rng.h"
#include "stride.h"

#include <Eigen/Dense>
#include <Eigen/Eigenvalues>

#include "denoise/denoise.h"
#include "denoise/estimate.h"
#include "denoise/estimator/estimator.h"
#include "denoise/estimator/imposed/unity.h"
#include "denoise/exports.h"
#include "denoise/iterative.h"
#include "denoise/kernel/cuboid.h"
#include "denoise/kernel/data.h"
#include "denoise/kernel/kernel.h"
#include "denoise/kernel/sphere_radius.h"
#include "denoise/kernel/sphere_minvoxels.h"
#include "denoise/mask.h"
#include "denoise/partition.h"
#include "denoise/precondition/noise_model/noise_model.h"
#include "denoise/precondition/preconditioner.h"
#include "denoise/recon.h"
#include "denoise/schedule.h"
#include "denoise/spatial_subsample.h"
#include "dwi/gradient.h"

using namespace MR;
using namespace App;
using namespace MR::Denoise;
using namespace MR::Denoise::Precondition;

// clang-format off
void usage() {

  SYNOPSIS = "Improved dMRI denoising using Marchenko-Pastur PCA";

  AUTHOR = "Robert E. Smith (robert.smith@florey.edu.au)"
           " and Daan Christiaens (daan.christiaens@kcl.ac.uk)"
           " and Jelle Veraart (jelle.veraart@nyumc.org)"
           " and J-Donald Tournier (jdtournier@gmail.com)";

  DESCRIPTION
  + "This command performs DWI data denoising,"
    " additionally with data-driven noise map estimation if not provided explicitly."
    " The output denoised DWI data is formed based on filtering of eigenvectors of PCA decompositions:"
    " for a set of patches each of which consists of a set of proximal voxels,"
    " the PCA decomposition is applied,"
    " and the DWI signal for those voxels is reconstructed"
    " where the contribution of each eigenvector is modulated based on its classification as noise."
    " In many use cases,"
    " a threshold that classifies eigenvalues as belonging to signal of interest vs. random thermal noise"
    " is based on the prior knowledge that the eigenspectrum of random covariance matrices"
    " is described by the universal Marchenko-Pastur (MP) distribution."

  + Denoise::patent_description

  + "This command includes many capabilities absent from the original MRtrix3 dwidenoise command. "
    "These include:"
    " - Multiple sliding window kernel shapes,"
      " including a spherical kernel that dilates at image edges to preserve aspect ratio;"
    " - A greater number of mechanisms for noise level estimation,"
      " including taking a pre-estimated noise map as input;"
    " - Preconditioning, including (per-shell) demeaning,"
      " phase demodulation (linear, Hann, or noise-adaptive),"
      " and variance-stabilising transform to compensate for within-patch heteroscedasticity;"
    " - Overcomplete local PCA;"
    " - Subsampling (performing fewer PCAs than there are input voxels);"
    " - Optimal shrinkage of eigenvalues;"
    " - Multi-resolution iterative optimisation."

  + "Where an a priori noise map or desired output signal rank is not specified,"
    " the noise map estimate is derived through an iterative multi-resolution pyramid."
    " In the earlier iterations, there are fewer PCAs performed"
    " in order to obtain a low-resolution and smooth noise map estimate."
    " These estimates are then used as input to subsequent iterations"
    " to apply a variance-stabilising transform prior to PCA,"
    " deriving a new noise map at a higher spatial resolution."
    " The noise map estimated in the second-last iteration is additionally smoothed."
    " In the final iteration, there is no noise level estimation performed;"
    " the noise map generated by the second-last iteration is used as an a priori noise map"
    " for both variance-stabilising transform and denoising."

  + Denoise::first_step_description

  + Denoise::non_gaussian_noise_description

  + "For magnitude (or multi-channel sum-of-squares) input data,"
    " the output by default has the noise-floor bias removed:"
    " the non-linear variance-stabilising transform is reversed by inverting it,"
    " for each individual sample, at that sample's own denoised value,"
    " mapping it back to the bias-free underlying signal level."
    " Because the inverse is evaluated per sample rather than being linearised about"
    " a per-volume-group mean,"
    " this debiasing is independent of the -demean grouping;"
    " it prevents the characteristic residual \"haze\" that otherwise appears"
    " in data denoised close to the noise floor,"
    " while the denoised fluctuations are returned on the original intensity scale."
    " This behaviour can be disabled using the -preserve_noise_bias option,"
    " in which case conventional biased-magnitude-scale output is produced (the noise floor is retained)."
    " The -debias_anchor option can instead select the legacy per-volume-group operating point."
    " For complex input data there is no such bias,"
    " and the output is unaffected by these options."

  + demodulation_description

  + Kernel::shape_description

  + Kernel::default_size_description

  + Kernel::cuboid_size_description

  + Denoise::filter_description

  + Denoise::aggregation_description

  + Schedule::schedule_description;

  EXAMPLES
  + Example("To approximately replicate the behaviour of the original dwidenoise command",
            "dwidenoise2 DWI.mif out.mif -vst_method none -demodulate none -demean none -filter truncate -aggregator exclusive -schedule legacy",
            "The bundled \"legacy\" schedule selects the cuboid sliding-window kernel used by the"
            " original command (there are no command-line kernel options; kernel shape and size are"
            " configured through the schedule)."
            " While this is neither guaranteed to match exactly the output of the original dwidenoise command"
            " nor is it a recommended use case,"
            " it may nevertheless be informative in demonstrating those advanced features of dwidenoise2 active by default"
            " that must be explicitly disabled in order to approximate that behaviour.")

  + Example("Denoising multi-echo fMRI data",
            "mrcat original_TE1.mif original_TE2.mif original_TE3.mif original_all.mif -axis 4;"
            " dwidenoise2 original_all.mif denoised_all.mif;"
            " for_each 1 2 3 : mrconvert denoised_all.mif denoised_TEIN.mif -coord 4 IN -axes 0,1,2,3",
            "By concatenating echoes along a new fifth image axis,"
            " the program will by default calculate the mean intensity per echo "
            " and regress this from the data prior to PCA; "
            " this should reduce the signal rank and increase PCA precision. "
            " One may also wish to consider the use of -filter thresh in the context of fMRI, "
            " as it results in the least variance loss (for a given noise level estimator) "
            " and therefore the least risk of BOLD signal attenuation.")

  + Example("Denoising a very large image series",
            "dwidenoise2 in.mif out.mif -schedule vlarge -decomposition selfadjoint",
            "There are some tweaks that can be applied to make computation more feasible"
            " for data larger than the typical DWI acquisition"
            " (including functional MRI data that may be multi-echo and/or long in duration)."
            " Provided schedule file \"vlarge.txt\" performs only a single noise level estimation step"
            " prior to the denoising step,"
            " rather than the default iterative multi-resolution approach."
            " In addition, more aggressive spatial subsampling is performed,"
            " only a fraction of the input series is used for initial noise level estimation,"
            " and the volumes within each PCA patch are broken into smaller partitions"
            " for which decompositions are performed independently,"
            " but across which a single noise level estimate applies. "
            " The self-adjoint decomposition is not as numerically precise as the newer BDCSVD decomposition"
            " but is typically around twice as fast."
            " Reducing the kernel size below the default aspect ratio is not recommended"
            " as it endangers erroneous noise level estimation and potentially biological signal removal.")

  + Example("Precompute noise estimation with dwi2noise, then denoise in a separate step",
            "dwi2noise DWI.mif noise.mif -rankpermm_out rpm.mif;"
            " dwidenoise2 DWI.mif out.mif -noise_in noise.mif -rankpermm_in rpm.mif -schedule apriori",
            "This splits the default single-command operation into the two phases of a typical"
            " image-correction pipeline: dwi2noise performs the iterative noise level estimation and"
            " exports both the noise level map (-noise_out / its primary output) and the per-voxel"
            " signal-rank density used to size the denoising kernel (-rankpermm_out); dwidenoise2 then"
            " consumes both via -noise_in and -rankpermm_in under the single-row \"apriori\" schedule"
            " (just the reconstruction pass), reproducing the result of a single default dwidenoise2 run."
            " Passing both maps is required for equivalence:"
            " -noise_in fixes the variance-stabilising transform and noise level,"
            " while -rankpermm_in reproduces the rank-adaptive kernel"
            " (omitting it falls back to a fixed aspect-ratio kernel).");

  COPYRIGHT =
  "Copyright (c) 2025 Robert E. Smith <robert.smith@florey.edu.au>;"
  " The Florey Institute of Neuroscience and Mental Health."
  " Licensed under the PolyForm Noncommercial License 1.0.0 (the \"License\");"
  " you may not use this file except in compliance with the License."
  " You may obtain a copy of the License at:"
  " https://polyformproject.org/licenses/noncommercial/1.0.0."
  " Unless required by applicable law or agreed to in writing,"
  " software distributed under the License is distributed on an \"AS IS\" BASIS,"
  " WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,"
  " either express or implied."
  " See the License of the specific language"
  " governing permissions and limitations under the License.";

  REFERENCES
  + "Veraart, J.; Novikov, D.S.; Christiaens, D.; Ades-aron, B.; Sijbers, J. & Fieremans, E. " // Internal
    "Denoising of diffusion MRI using random matrix theory. "
    "NeuroImage, 2016, 142, 394-406, doi: 10.1016/j.neuroimage.2016.08.016"

  + "Veraart, J.; Fieremans, E. & Novikov, D.S. " // Internal
    "Diffusion MRI noise mapping using random matrix theory. "
    "Magn. Res. Med., 2016, 76(5), 1582-1593, doi: 10.1002/mrm.26059"

  + "Cordero-Grande, L.; Christiaens, D.; Hutter, J.; Price, A.N.; Hajnal, J.V. " // Internal
    "Complex diffusion-weighted image estimation via matrix recovery under general noise models. "
    "NeuroImage, 2019, 200, 391-404, doi: 10.1016/j.neuroimage.2019.06.039"

  + "* If denoising complex data without changing -demodulate from its default (apc): "
    "Pizzolato, M.; Gilbert, G.; Thiran, J.-P.; Descoteaux, M.; Deriche, R. "
    "Adaptive phase correction of diffusion-weighted images. "
    "NeuroImage, 2020, 206, 116274, doi: 10.1016/j.neuroimage.2019.116274"

  + "* If using -estimator mrm2023 (the default): "
    "Olesen, J.L.; Ianus, A.; Ostergaard, L.; Shemesh, N.; Jespersen, S.N. "
    "Tensor denoising of multidimensional MRI data. "
    "Magnetic Resonance in Medicine, 2023, 89(3), 1160-1172"

  + "* If using -estimator tbme2022: "
    "Zhu, W.; Ma, X.; Zhu, X.-H.; Ugurbil, K.; Chen, W.; Wu, X. "
    "Denoise Functional Magnetic Resonance Imaging With Random Matrix Theory Based Principal Component Analysis. "
    "IEEE Transactions on Biomedical Engineering, 2022, 69(11), 3377-3388, doi: 10.1109/TBME.2022.3168592"

  + "* If using anything other than -aggregation exclusive: "
    "Manjon, J.V.; Coupe, P.; Concha, L.; Buades, A.; D. Collins, D.L.; Robles, M. "
    "Diffusion Weighted Image Denoising Using Overcomplete Local PCA. "
    "PLoS ONE, 2013, 8(9), e73021"

  + "* If using -estimator med or -filter optthresh: "
    "Gavish, M.; Donoho, D.L."
    "The Optimal Hard Threshold for Singular Values is 4/sqrt(3). "
    "IEEE Transactions on Information Theory, 2014, 60(8), 5040-5053.";

  ARGUMENTS
  + Argument("dwi", "the input diffusion-weighted image.").type_image_in()
  + Argument("out", "the output denoised DWI image.").type_image_out();

  OPTIONS
  + OptionGroup("Options for modifying PCA computations")
  + datatype_option
  + decomposition_option
  + Estimator::estimator_denoise_options
  + Option("rankpermm_in",
           "Import a precomputed signal-rank density (signal rank per mm of kernel radius),"
           " either as a scalar value or as a 3D image (e.g. exported by dwi2noise -rankpermm_out),"
           " to size the rank-adaptive reconstruction kernel."
           " This lets a single-row (e.g. \"apriori\") schedule reproduce the rank-adaptive kernel"
           " that the default multi-resolution schedule derives internally;"
           " it is rejected with a multi-row schedule, which builds the rank density itself.")
    + Argument("value/image").type_float(0.0).type_image_in()
  + Schedule::schedule_option
  + precondition_options(true)

  + OptionGroup("Options that affect reconstruction of the output image series")
  + Option("filter",
           "Modulate how component contributions are filtered "
           "based on the cumulative eigenvalues relative to the noise level; "
           "options are: " + Enum::join<filter_type>(",") + "; "
           "default: optshrink (Optimal Shrinkage based on minimisation of the Frobenius norm)")
    + Argument("choice").type_choice<filter_type>()
  + Option("aggregator",
           "Select how the outcomes of multiple PCA outcomes centred at different voxels "
           "contribute to the reconstructed DWI signal in each voxel; "
           "options are: " + Enum::join<aggregator_type>(",") + "; default: Gaussian")
    + Argument("choice").type_choice<aggregator_type>()
  + Option("aggregator_fwhm",
           "For the Gaussian aggregator only: "
           "the full width at half maximum (FWHM) of the spatial weighting function, "
           "expressed as a multiple of the spacing between adjacent PCA patches "
           "(i.e. the reconstruction sub-sample grid: sub-sample factor x voxel size). "
           "Larger values blend more strongly across neighbouring patches "
           "(greater variance reduction, but more spatial blurring); "
           "smaller values approach reconstruction from the nearest patch only. "
           "Default: 2.0 "
           "(the half-maximum then falls on the neighbouring patch centre).")
    + Argument("multiple").type_float(0.0)
  + Option("preserve_noise_bias",
           "retain the noise-floor bias in the output rather than removing it by default"
           " (no effect for complex input data)")
  + Option("debias_anchor",
           "operating point at which the non-linear variance-stabilising transform is inverted"
           " when removing the noise-floor bias; options are: " + Enum::join<debias_anchor_t>(",") + " "
           "(default: sample)."
           " 'sample' inverts the transform at each volume's own denoised value, so debiasing is"
           " independent of the -demean grouping;"
           " 'group_mean' reproduces the prior behaviour, linearising the inverse about the"
           " per-group demeaning mean"
           " (no effect with -preserve_noise_bias or for complex input data)")
    + Argument("mode").type_choice<debias_anchor_t>()

  + OptionGroup("Options for exporting additional data regarding PCA behaviour")
  + Option("noise_out",
           "The output noise map,"
           " i.e., the estimated noise level 'sigma' in the data. "
           "Note that on complex input data,"
           " this will be the total noise level across real and imaginary channels,"
           " so a scale factor sqrt(2) applies.")
    + Argument("image").type_image_out()
  + Option("lamplus",
           "The estimated upper bound of the noise portion of the eigenspectrum (\"lambda-plus\")")
    + Argument("image").type_image_out()
  + Option("rank_pcanonzero",
           "The (non-zero) rank of the PCA decomposition for each patch absent any denoising")
    + Argument("image").type_image_out()
  + Option("rank_input",
           "The estimated rank of the input data for each denoising patch")
    + Argument("image").type_image_out()
  + Option("rank_output",
           "An estimated rank for the output image data, accounting for multi-patch aggregation")
    + Argument("image").type_image_out()
  + Option("rankpermm_out",
           "Export the per-voxel signal-rank density (signal rank per mm of kernel radius) that was"
           " used to size the rank-adaptive reconstruction kernel."
           " For a multi-resolution schedule this is the density derived from the penultimate"
           " iteration; for a single-row schedule it is whatever was supplied via -rankpermm_in"
           " (nothing is written if no such density is available).")
    + Argument("image").type_image_out()
  + Option("variance_removed",
           "the fraction of variance removed in producing the output denoised data "
           "(note that this applies strictly to the PCA and omits effects of preconditioning)")
    + Argument("image").type_image_out()
  + Option("eigenspectra",
           "Output a matrix containing the spectra of eigenvalues across patches"
           " (one row per patch). Where volume partitioning is in effect, each row is the"
           " per-partition eigenspectra concatenated and sorted, normalised by partition size,"
           " rather than a single decomposition's spectrum.")
    + Argument("file").type_file_out()
  + Option("residual_statistics",
           "export images containing statistics of the residuals between input and denoised data,"
          " with image paths in order representing: mean, standard deviation, maxabs")
    + Argument("mean_image").type_image_out()
    + Argument("std_image").type_image_out()
    + Argument("maxabs_image").type_image_out()


  + OptionGroup("Options for debugging the operation of sliding window kernels")
  + Option("max_dist",
           "The maximum distance between a voxel and another voxel that was included in the local denoising patch")
    + Argument("image").type_image_out()
  + Option("voxelcount",
           "The number of voxels that contributed to the PCA for processing of each voxel")
    + Argument("image").type_image_out()
  + Option("patchcount",
           "The number of unique patches to which an image voxel contributes")
    + Argument("image").type_image_out()
  + Option("sum_aggregation",
           "The sum of aggregation weights of those patches contributing to each output voxel")
    + Argument("image").type_image_out()
  + Option("sum_optshrink",
           "the sum of eigenvector weights computed for the denoising patch centred at each voxel "
           "as a result of performing optimal shrinkage")
    + Argument("image").type_image_out()

  + DWI::GradImportOptions();

}
// clang-format on

// Necessary to allow normalisation by sum of aggregation weights
//   where the image type is cdouble, but aggregation weights are float
// (operations combining complex & real types not allowed to be of different precision)
std::complex<double> operator/(const std::complex<double> &c, const float n) { return c / double(n); }

// TODO Improve this
template <typename T>
typename std::enable_if<std::is_same<T, cfloat>::value, default_type>::type modulus(const cfloat in) {
  return Math::pow2(in.real()) + Math::pow2(in.imag());
}
template <typename T>
typename std::enable_if<std::is_same<T, cdouble>::value, default_type>::type modulus(const cdouble in) {
  return Math::pow2(in.real()) + Math::pow2(in.imag());
}
template <typename T> typename std::enable_if<!is_complex<T>::value, default_type>::type modulus(const T in) {
  return Math::pow2(in);
}

namespace {
// Voxel-wise functors for the final-output post-processing loops. ThreadedLoop copies the functor
//   per thread, so each thread holds independent Image accessors; all operations below are
//   voxel-local (or write voxel-disjoint volumes), so no locking is required.

// Copy one image's value into another, voxel for voxel.
struct CopyValueFunctor {
  template <class ImageOut, class ImageIn> void operator()(ImageOut &out, ImageIn &in) {
    out.value() = in.value();
  }
};

// Rescale overcomplete-aggregation output: divide every volume at a voxel by that voxel's
//   accumulated aggregation weight (voxels with zero weight are left unchanged). The 3-D weight
//   map is the looped image; a per-thread copy of the (4-D) preconditioned output is held as a
//   member and its volumes are updated in place.
template <typename T> class AggregationRescaleFunctor {
public:
  explicit AggregationRescaleFunctor(Image<T> &output_preconditioned)
      : output_preconditioned(output_preconditioned) {}
  void operator()(Image<float> &sum_aggregation) {
    const float sum = sum_aggregation.value();
    if (sum == 0.0F)
      return;
    const double multiplier = 1.0 / static_cast<double>(sum);
    assign_pos_of(sum_aggregation).to(output_preconditioned);
    for (auto l_volume = Loop(3)(output_preconditioned); l_volume; ++l_volume)
      output_preconditioned.value() *= multiplier;
  }

private:
  Image<T> output_preconditioned;
};

// Divide the per-voxel output rank by its accumulated aggregation weight (0 where the weight is 0).
struct RankOutputAggregationFunctor {
  void operator()(Image<float> &rank_output, Image<float> &sum_aggregation) {
    const float sum = sum_aggregation.value();
    rank_output.value() = sum == 0.0F ? 0.0F : (rank_output.value() / sum);
  }
};

// Add the preconditioner's demean null-rank back into the reported input rank (clamped to
//   max_rank), only for voxels carrying a non-zero estimated signal rank.
class RankInputAddbackFunctor {
public:
  RankInputAddbackFunctor(const uint16_t null_rank, const uint16_t max_rank)
      : null_rank(null_rank), max_rank(max_rank) {}
  void operator()(Image<uint16_t> &rank_input) {
    if (rank_input.value() > 0)
      rank_input.value() = std::min<uint16_t>(uint16_t(rank_input.value()) + null_rank, max_rank);
  }

private:
  uint16_t null_rank;
  uint16_t max_rank;
};

// Add the preconditioner's demean null-rank back into the reported output rank (clamped).
class RankOutputAddbackFunctor {
public:
  RankOutputAddbackFunctor(const float null_rank, const float max_rank)
      : null_rank(null_rank), max_rank(max_rank) {}
  void operator()(Image<float> &rank_output) {
    rank_output.value() = std::min<float>(float(rank_output.value()) + null_rank, max_rank);
  }

private:
  float null_rank;
  float max_rank;
};

// Per-voxel residual summary statistics. ThreadedLoop copies the functor per thread, so each thread
//   holds its own (private) Image accessors for the 4-D input and denoised output. At each spatial
//   voxel the functor runs an inner Welford accumulation across all supra-spatial (volume) axes, so
//   the mean and variance are aggregated per voxel over that voxel's own volumes only: the sample
//   count is the number of volumes at the voxel, not the whole-image element count. maxabs is the
//   largest residual magnitude across that voxel's volumes.
template <typename T> class ResidualStatsFunctor {
public:
  ResidualStatsFunctor(const Image<T> &input, const Image<T> &output) : input(input), output(output) {}
  void operator()(Image<T> &residuals_mean, Image<float> &residuals_std, Image<float> &residuals_maxabs) {
    assign_pos_of(residuals_mean, 0, 3).to(input, output);
    T mean(0.0);
    T m2(0.0);
    default_type maxabs = 0.0;
    size_t count = 0;
    for (auto l = Loop(3)(input, output); l; ++l) {
      const T diff = T(output.value()) - T(input.value());
      ++count;
      const T delta = diff - mean;
      mean += T(delta / default_type(count));
      const T delta2 = diff - mean;
      m2 += delta * delta2;
      maxabs = std::max(maxabs, default_type(std::abs(diff)));
    }
    residuals_mean.value() = mean;
    residuals_std.value() = std::sqrt(std::abs(m2) / default_type(count));
    residuals_maxabs.value() = maxabs;
  }

private:
  Image<T> input, output;
};
} // namespace

template <typename T>
void run(Header &dwi,
         const Demodulation &demodulation,
         const demean_type demean,
         Image<float> &user_vst_image,
         const std::vector<Iterative::Iteration> &iterations,
         const decomp_type decomposition,
         std::shared_ptr<Estimator::Base> estimator,
         filter_type filter,
         aggregator_type aggregator,
         const default_type aggregator_fwhm,
         const bias_handling_t bias_handling,
         const debias_anchor_t debias_anchor,
         const std::string &output_name,
         Exports &final_exports) {

  Image<T> input(dwi.get_image<T>());
  Image<bool> mask = generate_mask(input);
  Image<float> vst_image(user_vst_image);

  // Noise model governing the variance-stabilising transform, configured from
  //   the -noise_dof and -vst_method options (Gaussian for complex data).
  std::shared_ptr<NoiseModel::Base> noise_model = make_noise_model(is_complex<T>::value);

  Preconditioner<T> preconditioner(input, demodulation, demean, user_vst_image, noise_model);
  // Cold adaptive-phase-correction solves within the noise-estimation iterations below are
  //   bootstraps: the final (reconstruction) pass re-estimates every volume's phase at native
  //   resolution, so they may be solved on a 2x-downsampled grid. Cleared before that final pass
  //   (and never set for a single-row schedule, which has no such iterations).
  preconditioner.set_apc_refine_later(iterations.size() > 1);
  Image<T> input_preconditioned;

  // Per-voxel signal-rank density used to size the rank-adaptive reconstruction kernel. Normally
  //   accumulated across the noise-estimation iterations below; for a single-row schedule there are
  //   no such iterations, so an externally-supplied map (-rankpermm_in, e.g. exported by dwi2noise)
  //   may seed it. run() rejects -rankpermm_in with a multi-row schedule, so when the iteration loop
  //   runs it overwrites this seed (as intended) rather than mixing the two.
  Image<float> rank_per_mm;
  {
    auto opt_rpm_in = get_options("rankpermm_in");
    if (!opt_rpm_in.empty())
      rank_per_mm = Denoise::import_rank_per_mm_map(opt_rpm_in[0][0], dwi);
  }

  // Random number generator for drawing temporal sub-sampling subsets.
  Math::RNG rng;
  constexpr ssize_t temporal_min_per_group = 2;

  // All but the last iteration: estimate (and progressively refine) the noise level.
  for (ssize_t iteration = 0; iteration != iterations.size() - 1; ++iteration) {
    // Draw this iteration's temporal subset (stratified by demeaning group) and (re)compute
    //   the stabilised-domain per-group means over that same subset, under the current noise
    //   level map. The preconditioned data then hold only the m' subset volumes, so the
    //   downstream Estimate / kernel sizing see m' volumes without any knowledge of sub-sampling.
    preconditioner.set_temporal_subsample(iterations[iteration].temporal_subsample, rng, temporal_min_per_group);
    // Resolve the partition count for this iteration from the (post-subsampling) volume count m'.
    //   When partitioning, the preconditioner performs no demeaning (done per partition within
    //   Estimate); set this before update_parameters so it skips the now-unused mean pass.
    const ssize_t mprime = preconditioner.header().size(3);
    const ssize_t num_partitions = Iterative::resolve_num_partitions(iterations[iteration], mprime);
    if (num_partitions > 1 && !estimator->supports_partitioning())
      throw Exception("The selected noise level estimator does not support volume partitioning "
                      "(schedule iteration " + str(iteration + 1) + " requests " + str(num_partitions) +
                      " partitions); choose a different -estimator or remove partitioning from the schedule");
    preconditioner.set_partitioning_active(num_partitions > 1);
    preconditioner.update_parameters(vst_image, input);
    estimator->update_vst_image(vst_image);
    input_preconditioned =
        Image<T>::scratch(preconditioner.header(), "Preconditioned version of \"" + dwi.name() + "\"");

    // Per-kernel partitioning: each PCA patch draws its own balanced assignment (in Estimate,
    //   from a voxel-seeded RNG), so only the per-volume demeaning-group labels and the partition
    //   count are passed; no single shared (per-level) assignment is built.
    std::vector<ssize_t> volume_group;
    std::shared_ptr<const Partitioning> partitioning; // null ⇒ per-kernel in Estimate
    if (num_partitions > 1)
      volume_group = preconditioner.output_volume_to_group();

    std::shared_ptr<SpatialSubsample> subsample =
        std::make_shared<SpatialSubsample>(dwi, iterations[iteration].spatial_subsample_ratios);
    // For internal iterations, we only save the output noise level estimate
    Exports iteration_exports(dwi, subsample->header());
    iteration_exports.set_noise_out();
    iteration_exports.set_rank_input();
    iteration_exports.set_max_dist();
    Iterative::estimate(input,
                        input_preconditioned,
                        mask,
                        vst_image,
                        rank_per_mm,
                        iterations[iteration],
                        iteration,
                        subsample,
                        decomposition,
                        estimator,
                        preconditioner,
                        iteration_exports,
                        num_partitions,
                        partitioning,
                        volume_group);
    // Propagate result to next iteration
    vst_image = Denoise::condition_noise_map(iteration_exports.noise_out,
                                             noise_impute_type::NAN_TO_ZERO,
                                             noise_pad_type::PAD,
                                             iterations[iteration].smooth_noiseout);
    // Signal-rank density (per mm of kernel radius) used to size the next iteration's rank-based
    //   kernel. Under partitioning the rank-based kernel is sized from the smallest partition
    //   (m'/P), so the density must be *per partition*: rank_input is the signal rank summed over
    //   the iteration's num_partitions partitions, so divide by that count. num_partitions is the
    //   count for the iteration that produced rank_input (it may differ between iterations).
    rank_per_mm = Denoise::compute_rank_per_mm(iteration_exports.rank_input, iteration_exports.max_dist, num_partitions);
  }

  // Final (reconstruction) pass: the schedule's final row is validated to have
  //   temporal_subsample == 1, so all volumes are reconstructed. Clear any subset and
  //   recompute the full-data means under the final noise level map.
  preconditioner.set_temporal_subsample(1.0, rng, temporal_min_per_group);
  // No APC pass follows this one, so any volume the noise-estimation iterations sub-sampled away
  //   (never yet phase-estimated) must be solved cold at native resolution here rather than on the
  //   coarse bootstrap grid.
  preconditioner.set_apc_refine_later(false);
  // Resolve partitioning for the reconstruction pass (sized from the full volume count, as the
  //   final row's temporal_subsample is validated to be 1.0). Set before update_parameters
  //   so the (unused) preconditioner-side demeaning pass is skipped when partitioning.
  const ssize_t mprime_final = preconditioner.header().size(3);
  const ssize_t num_partitions = Iterative::resolve_num_partitions(iterations.back(), mprime_final);
  preconditioner.set_partitioning_active(num_partitions > 1);
  preconditioner.update_parameters(vst_image, input);
  estimator->update_vst_image(vst_image);

  auto subsample = std::make_shared<SpatialSubsample>(dwi, iterations.back().spatial_subsample_ratios);

  // Implementation from here differs to that of dwi2noise
  auto opt = get_options("preconditioned_input");
  if (!opt.empty())
    input_preconditioned = Image<T>::create(opt[0][0], preconditioner.header());
  else
    input_preconditioned =
        Image<T>::scratch(preconditioner.header(), "Preconditioned version of \"" + dwi.name() + "\"");

  // Optionally export the signal-rank density that sizes the reconstruction kernel (the same quantity
  //   dwi2noise -rankpermm_out exports). Available only when a noise-estimation iteration derived it
  //   or it was supplied via -rankpermm_in; a bare single-row schedule has none.
  opt = get_options("rankpermm_out");
  if (!opt.empty()) {
    if (rank_per_mm.valid()) {
      Header H_rpm(rank_per_mm);
      Image<float> rpm_out = Image<float>::create(opt[0][0].as_text(), H_rpm);
      ThreadedLoop(rpm_out).run(CopyValueFunctor(), rpm_out, rank_per_mm);
    } else {
      WARN("-rankpermm_out: no signal-rank density is available to export "
           "(the schedule performed no noise-estimation iteration and none was supplied via "
           "-rankpermm_in); nothing written");
    }
  }

  // Final (reconstruction) pass: kernel type/parameter from the final schedule row (a rank-adaptive
  //   "rank" kernel by default, n >= m+r). Build the predicted-RMSE model from the estimator only if
  //   that row uses an RMSE kernel; the estimator is still the data-driven one here (the Unity
  //   substitution below happens afterwards).
  Kernel::predicted_rmse_func final_prmse;
  if (iterations.back().kernel.type == Kernel::kernel_spec_type::RMSE)
    // Capture the estimator by value: the kernel calls this during reconstruction, after the
    //   data-driven estimator may have been replaced below by the dummy Unity estimator.
    final_prmse = [estimator](ssize_t mm, ssize_t nn, double rr) { return estimator->predicted_rmse(mm, nn, rr); };
  auto kernel = Kernel::make_kernel(input_preconditioned,
                                    subsample->get_factors(),
                                    iterations.back().kernel,
                                    rank_per_mm,
                                    Denoise::num_volumes(input),
                                    num_partitions,
                                    final_prmse);
  kernel->set_mask(mask);

  // Unless the final schedule row is configured to (re)estimate the noise level, assume the
  //   variance-stabilising transform yields a noise level of 1.0 everywhere (dummy Unity
  //   estimator), carrying through the estimate refined by the preceding iterations.
  if (!iterations.back().update_noise.value())
    estimator.reset(new Estimator::Unity());

  if (num_partitions > 1 && !estimator->supports_partitioning())
    throw Exception("The selected noise level estimator does not support volume partitioning "
                    "(final schedule row requests " + str(num_partitions) +
                    " partitions); choose a different -estimator or remove partitioning from the schedule");
  if (num_partitions > 1 && debias_anchor == debias_anchor_t::GROUP_MEAN)
    throw Exception("The GROUP_MEAN debias anchor is incompatible with volume partitioning; "
                    "use -debias_anchor sample (the default) when partitioning is enabled");

  // Per-kernel partitioning (see the estimation loop above): pass only the demeaning-group
  //   labels and the partition count; Recon's Estimate base draws a per-patch assignment.
  std::vector<ssize_t> volume_group;
  std::shared_ptr<const Partitioning> partitioning; // null ⇒ per-kernel in Estimate/Recon
  if (num_partitions > 1)
    volume_group = preconditioner.output_volume_to_group();

  preconditioner(input, input_preconditioned, false);
  Recon<T> func(input_preconditioned,
                subsample,
                kernel,
                decomposition,
                estimator,
                filter,
                aggregator,
                aggregator_fwhm,
                final_exports,
                preconditioner.null_rank(),
                partitioning,
                volume_group,
                num_partitions);

  Header H_out (dwi);
  H_out.datatype() = DataType::from<T>();
  Image<T> output = Image<T>::create(output_name, H_out);
  Image<T> output_preconditioned;
  opt = get_options("preconditioned_output");
  if (!opt.empty())
    output_preconditioned = Image<T>::create(opt[0][0], preconditioner.header());
  // If we can make use of the output image for preconditioned denoised data
  //   rather than explicitly allocating an intermediate scratch buffer for that purpose,
  //   then do so
  else if (DataType::from<T>() == dwi.datatype() && dwi.ndim() == 4)
    output_preconditioned = output;
  else
    output_preconditioned = Image<T>::scratch(                              //
        preconditioner.header(),                                            //
        "Scratch buffer for denoised data before undoing preconditioning"); //

  const bool final_iteration_includes_MP =
      iterations.back().update_noise.value() && get_options("fixed_rank").empty();
  ThreadedLoop(final_iteration_includes_MP                                 //
                   ? "running MP-PCA noise level estimation and denoising" //
                   : "running PCA denoising",                              //
               input_preconditioned,                                       //
               0,                                                          //
               3)                                                          //
      .run(func, input_preconditioned, output_preconditioned);             //
  func.report_warnings();
  // Note: Denoise::condition_noise_map() is intentionally _not_ called here:
  //   noise estimates are fed through as-is

  const size_t max_rank = Denoise::num_volumes(dwi);

  // Rescale output if aggregation was performed
  if (aggregator != aggregator_type::EXCLUSIVE) {
    ThreadedLoop(final_exports.sum_aggregation)
        .run(AggregationRescaleFunctor<T>(output_preconditioned), final_exports.sum_aggregation);
    if (final_exports.rank_output.valid()) {
      ThreadedLoop(final_exports.sum_aggregation)
          .run(RankOutputAggregationFunctor(), final_exports.rank_output, final_exports.sum_aggregation);
    }
  }

  // reverse effects of preconditioning
  preconditioner(output_preconditioned, output, true, bias_handling, debias_anchor);

  // Modify some optional outputs to better reflect utilisation of preconditioning. The
  //   group-mean components regressed out by demeaning are added back to the reported ranks here,
  //   on the final maps only (the per-iteration rank_input fed to the kernel sizing is kept
  //   mean-free). demean_rank() gives the group count whether the demeaning was applied by the
  //   preconditioner (no partitioning) or per partition within Estimate/Recon (partitioning), so
  //   the demean-induced rank contribution is identical in both regimes.
  const ssize_t preconditioner_null_rank = preconditioner.demean_rank();
  if (preconditioner_null_rank > 0) {
    if (final_exports.rank_input.valid()) {
      ThreadedLoop(final_exports.rank_input)
          .run(RankInputAddbackFunctor(uint16_t(preconditioner_null_rank), uint16_t(max_rank)),
               final_exports.rank_input);
    }
    if (final_exports.rank_output.valid()) {
      ThreadedLoop(final_exports.rank_output)
          .run(RankOutputAddbackFunctor(float(preconditioner_null_rank), float(max_rank)),
               final_exports.rank_output);
    }
  }
  if (vst_image.valid()) {
    if (final_exports.noise_out.valid()) {
      ThreadedLoop(final_exports.noise_out)
          .run(NoiseMapVSTRescaleFunctor(vst_image, subsample->header()), final_exports.noise_out);
    }
    if (final_exports.lamplus.valid()) {
      // Note: each lamplus voxel is scaled by the noise level interpolated at *its own* scanner
      //   position (the looped image's index), correcting a prior copy-paste that sampled
      //   final_exports.noise_out's index here.
      ThreadedLoop(final_exports.lamplus)
          .run(NoiseMapVSTRescaleFunctor(vst_image, subsample->header()), final_exports.lamplus);
    }
  }

  opt = get_options("residual_statistics");
  if (!opt.empty()) {
    Header H_resstats_complex(dwi);
    if (dwi.datatype().is_integer()) {
      H_resstats_complex.datatype() = DataType::Float32;
      H_resstats_complex.datatype().set_byte_order_native();
    }
    H_resstats_complex.ndim() = 3;
    Header H_resstats_real(H_resstats_complex);
    H_resstats_real.datatype() = DataType::Float32;
    H_resstats_real.datatype().set_byte_order_native();
    Image<T> residuals_mean = Image<T>::create(opt[0][0], H_resstats_complex);
    Image<float> residuals_std = Image<float>::create(opt[0][1], H_resstats_real);
    Image<float> residuals_maxabs = Image<float>::create(opt[0][2], H_resstats_real);
    // Per-voxel residual statistics: multi-thread over one spatial axis (the outer, slice axis) with
    //   the two in-slice spatial axes iterated per thread; the Welford mean/variance accumulation
    //   across all supra-spatial axes runs inside the functor, so each voxel's statistics are
    //   aggregated over that voxel's volumes only.
    ThreadedLoop("Computing statistics of denoising residuals", residuals_mean,
                 std::vector<size_t>({2}), std::vector<size_t>({0, 1}))
        .run(ResidualStatsFunctor<T>(input, output), residuals_mean, residuals_std, residuals_maxabs);
  }
}

void run() {
  auto dwi = Header::open(argument[0]);
  if (dwi.ndim() < 4)
    throw Exception("input image must be at least 4-dimensional");
  if (Denoise::num_volumes(dwi) == 1)
    throw Exception("input image must be non-singleton across non-spatial dimensions");

  const Demodulation demodulation = select_demodulation(dwi);
  const demean_type demean = select_demean(dwi);
  const decomp_type decomposition = get_option_choice("decomposition", default_decomposition);

  // Resolve the requested variance-stabilising transform up-front:
  //   -vst_method none disables the transform entirely, which makes iterative
  //   refinement of the noise level pointless (handled below) and is incompatible
  //   with -noise_in (which exists only to parameterise the transform).
  const NoiseModel::vst_method_t vst_method =
      get_option_choice("vst_method", NoiseModel::vst_method_t::FOI);
  const bool vst_none = (vst_method == NoiseModel::vst_method_t::NONE);

  // A pre-estimated noise level provided via -noise_in is authoritative:
  //   it parameterises the variance-stabilising transform (the VST scale),
  //   and via the Fixed/Import estimator (make_estimator below) it bypasses
  //   noise level estimation, yielding sigma^2 ~ 1 on the stabilised data
  //   (equivalent to -estimator unity); see vst_plan.md section 6.2.
  Image<float> user_vst_image;
  auto opt = get_options("noise_in");
  if (!opt.empty()) {
    if (vst_none)
      throw Exception("Options -noise_in and -vst_method none are incompatible: "
                      "a pre-estimated noise level is used to parameterise the variance-stabilising transform, "
                      "which is disabled by -vst_method none");
    if (demean == demean_type::NONE) {
      WARN("Application of variance-stabilising transform in the absence of demeaning may be erroneous");
    }
    user_vst_image = Denoise::import_vst_noise_map(opt[0][0], dwi);
  }

  const aggregator_type aggregator = get_option_choice("aggregator", aggregator_type::GAUSSIAN);

  // Width of the Gaussian aggregator, as a multiple of the inter-patch spacing (see -aggregator_fwhm).
  //   It parameterises only the Gaussian weighting function, so reject an explicit request for any
  //   other aggregator rather than silently ignoring it. type_float(0.0) already excludes negative
  //   values; a value of exactly zero is additionally rejected as it would collapse the weighting.
  const default_type aggregator_fwhm = get_option_value("aggregator_fwhm", default_aggregator_fwhm);
  if (!get_options("aggregator_fwhm").empty()) {
    if (aggregator != aggregator_type::GAUSSIAN)
      throw Exception("Option -aggregator_fwhm only applies to the Gaussian aggregator "
                      "(-aggregator gaussian); it has no meaning for the requested aggregator");
    if (!(aggregator_fwhm > 0.0))
      throw Exception("Value provided to -aggregator_fwhm must be greater than zero");
  }

  const bias_handling_t bias_handling =
      get_options("preserve_noise_bias").empty() ? bias_handling_t::DEBIAS : bias_handling_t::PRESERVE;
  // -preserve_noise_bias governs how the noise-floor bias of the magnitude noise
  //   distribution is handled when reversing the variance-stabilising transform. It is
  //   meaningless whenever the noise model is linear (Gaussian / identity), i.e. when there
  //   is no estimated noise bias to either preserve or remove. This linear case arises from
  //   complex input data (Gaussian noise) or from the user requesting a linear transform
  //   (-vst_method none / linear) on the command line; mirrors make_noise_model().
  if (bias_handling == bias_handling_t::PRESERVE) {
    const bool complex = dwi.datatype().is_complex();
    const bool vst_linear = (vst_method == NoiseModel::vst_method_t::LINEAR);
    if (complex || vst_none || vst_linear) {
      const std::string reason =
          vst_none    ? "-vst_method none applies no variance-stabilising transform"               //
          : complex   ? "the input data are complex, for which the noise is Gaussian-distributed"   //
                      : "-vst_method linear uses a linear (Gaussian) noise model";                  //
      WARN("Option -preserve_noise_bias has no effect: " + reason + ", "
           "so the noise model is linear and there is no estimated noise bias "
           "to either preserve or remove");
    }
  }

  // Operating point for reversing the non-linear variance-stabilising transform when debiasing
  //   (see debias_anchor_t); the default inverts the transform at each volume's own denoised
  //   value, so debiasing no longer depends on the demeaning grouping.
  const debias_anchor_t debias_anchor = get_option_choice("debias_anchor", debias_anchor_t::SAMPLE);

  // Resolve the iteration schedule. When the user supplies -schedule it is the single
  //   source of truth for both the spatial and temporal sub-sampling of each iteration;
  //   otherwise the command's bundled default schedule is loaded from file (Schedule::load_default).
  //   "one-pass" operation is simply a single-row schedule. -fixed_rank imposes a constant signal
  //   rank and reduces to a dedicated single-pass schedule (see below); -vst_method none removes
  //   the coupling between iterations and likewise reduces to a single-iteration schedule.
  std::vector<Iterative::Iteration> iterations;
  const bool fixed_rank = !get_options("fixed_rank").empty();
  if (Schedule::requested()) {
    iterations = Schedule::load("dwidenoise2");
    // Without a variance-stabilising transform there is no coupling between iterations, so the
    //   per-iteration refinement of a multi-row schedule cannot propagate and is wasted
    //   computation; a single-row schedule (e.g. the bundled "legacy" schedule) is, however,
    //   perfectly meaningful under -vst_method none.
    if (vst_none && iterations.size() > 1)
      throw Exception("Option -vst_method none cannot be combined with a -schedule of more than "
                      "one row: without a variance-stabilising transform there is no coupling "
                      "between iterations for the additional schedule rows to control; "
                      "use a single-row schedule");
  } else if (fixed_rank) {
    // -fixed_rank selects the imposed (constant) fixed-rank estimator. A fixed rank does not yield
    //   a robust data-driven noise level, so its estimate is not used to refine the
    //   variance-stabilising transform: this is a single denoising pass, not an iterative schedule.
    //   The bundled single-row "fixedrank" schedule sizes the kernel to n = m + r (the "rank_fixed"
    //   kernel, which reads r from -fixed_rank).
    iterations = Schedule::load_bundled("dwidenoise2", "fixedrank");
  } else if (vst_none) {
    WARN("-vst_method none: no variance-stabilising transform is applied, so iteratively "
         "refining the noise level estimate would have no effect on subsequent iterations "
         "and is therefore wasted computation; performing a single pass instead");
    const ssize_t f = (aggregator == aggregator_type::EXCLUSIVE) ? ssize_t(1) : default_spatial_subsample_ratio;
    Iterative::Iteration config;
    config.spatial_subsample_ratios = {f, f, f};
    // Single pass (no prior rank map): aspect ratio n ~ 2m.
    config.kernel.type = Kernel::kernel_spec_type::ASPECT_RATIO;
    config.kernel.param = 2.0;
    config.smooth_noiseout = noise_smooth_type::NONE;
    config.temporal_subsample = 1.0;
    config.update_noise = true; // a single-pass schedule must estimate the noise level
    iterations.push_back(config);
  } else {
    iterations = Schedule::load_default("dwidenoise2");
    Schedule::warn_if_default_schedule_slow(Denoise::num_volumes(dwi));
  }
  std::shared_ptr<SpatialSubsample> final_subsample =
      std::make_shared<SpatialSubsample>(dwi, iterations.back().spatial_subsample_ratios);

  // Resolve per-iteration update_noise defaults: non-final unset -> true; final unset ->
  //   false (carry the prior estimate through the reconstruction via the dummy Unity estimator).
  for (size_t i = 0; i + 1 < iterations.size(); ++i)
    if (!iterations[i].update_noise.has_value())
      iterations[i].update_noise = true;
  if (!iterations.back().update_noise.has_value())
    iterations.back().update_noise = false;

  // smooth_noise smooths an iteration's freshly estimated noise map before it is passed on; that
  //   is only meaningful when the iteration (re)estimates the noise level. With update_noise now
  //   resolved, reject any iteration that requests smoothing without estimating (the final
  //   reconstruction row, whose update_noise defaults to false, is the only one that can reach
  //   here, as non-final rows are already required to have update_noise true).
  for (const auto &it : iterations)
    if (it.smooth_noiseout == noise_smooth_type::SMOOTH && !it.update_noise.value())
      throw Exception("A schedule iteration sets smooth_noise true but does not (re)estimate the "
                      "noise level in that iteration (update_noise false), so there is no freshly "
                      "estimated noise map to smooth; smooth_noise may be true only when "
                      "update_noise is true in the same iteration");

  // dwidenoise2's final (reconstruction) pass must reconstruct every volume.
  if (iterations.back().temporal_subsample < 1.0)
    throw Exception("dwidenoise2 requires the final (reconstruction) schedule row to use all "
                    "volumes (temporal_subsample = 1); sub-sample only the noise-estimation iterations");
  // -fixed_rank is a single denoising pass with the imposed fixed-rank estimator, sized to the
  //   n = m + r ("rank_fixed") kernel. Its noise level estimate is not robust enough to drive the
  //   variance-stabilising transform, so multi-row (iterative) schedules are disallowed; and every
  //   row must use the "rank_fixed" kernel (the default bundled "fixedrank" schedule satisfies
  //   both when -fixed_rank is given without -schedule).
  if (fixed_rank) {
    if (iterations.size() > 1)
      throw Exception("Option -fixed_rank performs a single denoising pass (a fixed-rank noise level "
                      "estimate is not used to refine the variance-stabilising transform) and cannot "
                      "be combined with a multi-row schedule; use the bundled single-row \"fixedrank\" "
                      "schedule (the default when -fixed_rank is given without -schedule)");
    for (const auto &it : iterations)
      if (it.kernel.type != Kernel::kernel_spec_type::RANK_FIXED)
        throw Exception("Option -fixed_rank requires the schedule to use the \"rank_fixed\" (n = m + r) "
                        "kernel; use the bundled \"fixedrank\" schedule (the default when -fixed_rank "
                        "is given without -schedule)");
  } else {
    // The "rank_fixed" kernel (n = m + r) has no defined r without an imposed fixed rank.
    for (const auto &it : iterations)
      if (it.kernel.type == Kernel::kernel_spec_type::RANK_FIXED)
        throw Exception("A schedule uses the \"rank_fixed\" kernel (n = m + r) but no fixed signal rank "
                        "was provided; supply -fixed_rank <value> (or use a different kernel)");
  }
  // Some source must establish the noise level: at least one estimating iteration, or a -noise_in seed.
  {
    bool any_update = false;
    for (const auto &it : iterations)
      any_update = any_update || it.update_noise.value();
    if (!any_update && get_options("noise_in").empty())
      throw Exception("The schedule never estimates the noise level (every update_noise is false) "
                      "and no -noise_in seed was provided; there is no noise level with which to denoise");
  }
  // For a multi-stage schedule, -noise_in only seeds the first iteration; the noise map used to
  //   denoise is re-estimated internally and differs from the supplied image.
  if (!get_options("noise_in").empty() && iterations.size() > 1)
    WARN("Option -noise_in provides only an initial noise level seed for the iterative schedule; "
         "the noise map used to denoise the data is re-estimated internally and differs from the "
         "supplied image");

  // -rankpermm_in seeds the reconstruction kernel's signal-rank density. A multi-resolution schedule
  //   derives that density itself from its noise-estimation iterations, so a supplied map would only
  //   affect the first iteration's kernel and then be discarded; reject the combination outright. The
  //   option is meaningful with a single-row (e.g. "apriori") schedule, which has no such iteration.
  if (!get_options("rankpermm_in").empty() && iterations.size() > 1)
    throw Exception("Option -rankpermm_in provides a precomputed signal-rank density to size the "
                    "reconstruction kernel and is only meaningful with a single-row schedule (e.g. "
                    "the bundled \"apriori\" schedule); a multi-row schedule derives that density "
                    "internally from its noise-estimation iterations");

  // The exclusive aggregator assigns each voxel only the result of its own patch; if the final
  //   (reconstruction) iteration sub-samples space, the majority of voxels are never the centre
  //   of a patch and would be left empty in the output. Reject this combination outright rather
  //   than producing a mostly-empty denoised series.
  if (aggregator == aggregator_type::EXCLUSIVE &&
      *std::max_element(final_subsample->get_factors().begin(), final_subsample->get_factors().end()) > 1)
    throw Exception("Option -aggregator exclusive cannot be combined with a schedule whose final "
                    "(reconstruction) iteration performs non-unity spatial sub-sampling, as the "
                    "majority of output voxels would be left empty (only voxels at the centre of a "
                    "patch are reconstructed); use unity spatial sub-sampling on the final iteration "
                    "(e.g. the bundled \"legacy\" schedule)");

  auto estimator = Estimator::make_estimator(user_vst_image, true);

  const filter_type filter = get_option_choice(
      "filter", get_options("fixed_rank").empty() ? filter_type::OPTSHRINK : filter_type::TRUNCATE);

  Exports final_exports(dwi, final_subsample->header());
  opt = get_options("noise_out");
  if (!opt.empty())
    final_exports.set_noise_out(opt[0][0].as_text());
  opt = get_options("lamplus");
  if (!opt.empty())
    final_exports.set_lamplus(opt[0][0].as_text());
  opt = get_options("rank_pcanonzero");
  if (!opt.empty())
    final_exports.set_rank_pcanonzero(opt[0][0].as_text());
  opt = get_options("rank_input");
  if (!opt.empty())
    final_exports.set_rank_input(opt[0][0].as_text());
  opt = get_options("rank_output");
  if (!opt.empty()) {
    if (aggregator == aggregator_type::EXCLUSIVE && filter == filter_type::TRUNCATE) {
      WARN("When using -aggregator exclusive and -filter truncate, "
           "the output of -rank_output will be identical to the output of -rank_input, "
           "as there is no aggregation of multiple patches per output voxel "
           "and no optimal shrinkage to reduce output rank relative to estimated input rank");
    }
    final_exports.set_rank_output(opt[0][0].as_text());
  }
  opt = get_options("sum_optshrink");
  if (!opt.empty()) {
    if (filter == filter_type::TRUNCATE) {
      WARN("Note that with a truncation filter, "
           "output image from -sumweights option will be equivalent to rank_input");
    }
    final_exports.set_sum_optshrink(opt[0][0].as_text());
  }
  opt = get_options("max_dist");
  if (!opt.empty())
    final_exports.set_max_dist(opt[0][0].as_text());
  opt = get_options("voxelcount");
  if (!opt.empty())
    final_exports.set_voxelcount(opt[0][0].as_text());
  opt = get_options("patchcount");
  if (!opt.empty())
    final_exports.set_patchcount(opt[0][0].as_text());
  opt = get_options("sum_aggregation");
  if (!opt.empty()) {
    if (aggregator == aggregator_type::EXCLUSIVE) {
      WARN("Output from -sum_aggregation will just contain 1 for every voxel processed: "
           "no patch aggregation takes place when output series comes exclusively from central patch");
    }
    final_exports.set_sum_aggregation(opt[0][0].as_text());
  } else if (aggregator != aggregator_type::EXCLUSIVE) {
    final_exports.set_sum_aggregation();
  }
  opt = get_options("variance_removed");
  if (!opt.empty())
    final_exports.set_variance_removed(opt[0][0].as_text());
  opt = get_options("eigenspectra");
  if (!opt.empty())
    final_exports.set_eigenspectra_path(opt[0][0].as_text());

  int prec = (get_option_choice("datatype", dtype_t::FLOAT32) == dtype_t::FLOAT64) ? 1 : 0;
  if (dwi.datatype().is_complex())
    prec += 2; // support complex input data
  switch (prec) {
  case 0:
    assert(demodulation.axes.empty());
    INFO("select real float32 for processing");
    run<float>(         //
        dwi,            //
        demodulation,   //
        demean,         //
        user_vst_image, //
        iterations,     //
        decomposition,  //
        estimator,      //
        filter,          //
        aggregator,      //
        aggregator_fwhm, //
        bias_handling,   //
        debias_anchor,  //
        argument[1].as_text(), //
        final_exports); //
    break;
  case 1:
    assert(demodulation.axes.empty());
    INFO("select real float64 for processing");
    run<double>(        //
        dwi,            //
        demodulation,   //
        demean,         //
        user_vst_image, //
        iterations,     //
        decomposition,  //
        estimator,      //
        filter,          //
        aggregator,      //
        aggregator_fwhm, //
        bias_handling,   //
        debias_anchor,  //
        argument[1].as_text(), //
        final_exports); //
    break;
  case 2:
    INFO("select complex float32 for processing");
    run<cfloat>(        //
        dwi,            //
        demodulation,   //
        demean,         //
        user_vst_image, //
        iterations,     //
        decomposition,  //
        estimator,      //
        filter,          //
        aggregator,      //
        aggregator_fwhm, //
        bias_handling,   //
        debias_anchor,  //
        argument[1].as_text(), //
        final_exports); //
    break;
  case 3:
    INFO("select complex float64 for processing");
    run<cdouble>(       //
        dwi,            //
        demodulation,   //
        demean,         //
        user_vst_image, //
        iterations,     //
        decomposition,  //
        estimator,      //
        filter,          //
        aggregator,      //
        aggregator_fwhm, //
        bias_handling,   //
        debias_anchor,  //
        argument[1].as_text(), //
        final_exports); //
    break;
  }
}
